### ISSUE TITLE
Sample ABCI not working with Docker

### ISSUE THREAD

**Issue by Andlinks-Yourturn** [tendermint/abci#104]
Hello, 
I tried run `docker run --rm golang:1.8 sh -c  "go get  github.com/tendermint/abci/cmd/...  && exec dummy"`
It semms there's problem downloading dependencies.
`https fetch failed: Get https://golang.org/x/net/context?go-get=1: unexpected EOF`

**Comment by melekes** [comment]
Are you able to ping `golang.org`? If not, there is not much we can do except maybe suggesting checking for firewalls and/or using VPNs

**Comment by Andlinks-Yourturn** [comment]
@melekes Yes, `ping golang.org` works.

**Comment by melekes** [comment]
from inside docker? what type of network is u using?

**Comment by adrianbrink** [comment]
Can you chek the following:

```
docker --version
```

and 

```
docker run hello-world
```

Do both work? Also, what operating system are you on?

**Comment by Andlinks-Yourturn** [comment]
The docker version is
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:10:54 2017
 OS/Arch:      linux/amd64
 Experimental: false

And docker run hello-world works fine.

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

My OS is Ubuntu.

**Comment by Andlinks-Yourturn** [comment]
`docker run golang:1.8 sh -c "ping golang.org"`  
It returns: 
PING golang-consa.l.google.com (216.239.37.1): 56 data bytes
64 bytes from 216.239.37.1: icmp_seq=0 ttl=49 time=35.488 ms
64 bytes from 216.239.37.1: icmp_seq=1 ttl=49 time=35.593 ms

**Comment by zramsay** [comment]
@Andlinks-Yourturn did you get this working?

**Comment by melekes** [comment]
I think it was a temporary fluke. Retry after some time should help.

**Comment by melekes** [comment]
I think it was a temporary fluke. Retry after some time should help.
