### ISSUE TITLE
GRPC: speed up tx delivery using bidirectional streaming 

### ISSUE THREAD

**Issue by mdyring** [tendermint/abci#112]
Feature request:

Change ABCI over gRPC to "CheckTxs" and "DeliverTxs", i.e. provide all TXs in a single RPC call and use bidirectional gRPC streaming.

A bit of .proto says a thousand words:

service ABCIApplication {
...
	rpc DeliverTxs(stream RequestDeliverTx) returns (stream ResponseDeliverTx);
	rpc CheckTxs(stream RequestCheckTx) returns (stream ResponseCheckTx);
...
}
See "bidirectional streaming" on https://grpc.io/docs/guides/concepts.html.

This should significantly reduce the performance gap of gRPC ABCI and socket ABCI by avoiding the roundtrip for each Check/DeliverTx invocation.

**Comment by odeke-em** [comment]
@ebuchman @zramsay what's the consensus here? Should we be moving forward with this or can it wait?

**Comment by zramsay** [comment]
closing for https://github.com/tendermint/tendermint/issues/688 (lol)
