### ISSUE TITLE
Connection error module=abci-server error=EOF

### ISSUE THREAD

**Issue by paulrd** [tendermint/abci#125]
I get this error while running the dummy or counter app and sending messages via the cli.

**Comment by melekes** [comment]
Could you please share the logs or sequence of steps?

**Comment by paulrd** [comment]
1. In first teminal launch abci-cli counter
2. In another terminal run abci-cli check_tx 0x00
3. In first terminal output is:
```bash
I[11-09|12:48:26.882] Starting ABCIServer                          module=abci-server impl=ABCIServer
I[11-09|12:48:26.882] Waiting for new connection...                module=abci-server 
I[11-09|12:48:51.347] Accepted a new connection                    module=abci-server 
I[11-09|12:48:51.347] Waiting for new connection...                module=abci-server 
E[11-09|12:48:51.350] Connection error                             module=abci-server error=EOF
```
The counter app and abci-cli otherwise perform as intended, so I'm wondering if this connection error is also intended. Looking at the code, it seems that reading from the socket is not blocking as I would expect while there is not a message yet. It probably reads the first message ok, then looks for the next one and gets EOF unstead of a blocking read. I don't think I understand the intended functionality.

**Comment by paulrd** [comment]
Ok, I think I see the problem. The call to types.ReadMessage [here](https://github.com/tendermint/abci/blob/dc33aad9b4e514a2322725ef68f27f72d955c537/server/socket_server.go#L147) should be a blocking call or at least block somewhere along the call stack from there (ReadByteSlice->ReadVarint->ReadUInt8->ReadByte->ReadFull). Possibly by just calling ReadAt instead of ReadFull at the appropriate time so that we get a blocking read instead of EOF when the client has not yet closed the connection but no data is waiting. This will be performant as the call to ReadMessage is already in a go routine. At cursory glance, this may be a bug that could cause a lot of EOF signals to come on the channel when they should not.

**Comment by paulrd** [comment]
I think I'm wrong. There shouldn't be any 'non-blocking' read functions. I'm having a hard time getting the definitive answer looking around the net.

**Comment by paulrd** [comment]
In any case, even with pull request #129, the abci-cli dummy and counter apps close their connections after every command despite the abci documentation saying otherwise. I'm new to golang and haven't been able to figure out why.

**Comment by melekes** [comment]
the abci-cli dummy and counter apps do not close their connections. rather `abci-cli console` or `abci-cli check_tx`, etc. do after every command. this is not really an error per se. we should probably silent the logger in this case.

**Comment by paulrd** [comment]
Thanks for the reply, but I made an error in my last reply. It's the abci-cli console (and batch) commands that appear to be closing their connections after every command when the documentation explicitly says that they do not. Either it's a bug in the code or the documentation.

**Comment by ebuchman** [comment]
This is a bug introduced in the `console` in the latest release. When sending a command from the command line direct, we open a connection , send the command, and close. The error is expected then. However in the console, we should open the connection once, and be able to send many commands without any connection closing/error. See https://github.com/tendermint/abci/issues/133 for new issue to fix this.
