### ISSUE TITLE
abci-cli console/batch shouldn't open a new connection with each command

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#133]
See https://github.com/tendermint/abci/issues/125

**Comment by zramsay** [comment]
i think this was fixed in the last hour, i am able to run `abci-cli counter` then `abci-cli console` and walk through the tutorial. While the connection itself doesn't close, there is a log that it id (`Connection was closed by client`) even tho it stays open. There's a bunch of errors WRT to the tutorial:
```
> echo hello
-> code: OK
-> data: hello
-> data.hex: 0x68656C6C6F

> info
-> code: OK
-> data: {"hashes":0,"txs":0}
-> data.hex: 0x7B22686173686573223A302C22747873223A307D

> commit
-> code: OK

> deliver_tx "abc"
-> code: OK

> info
-> code: OK
-> data: {"hashes":1,"txs":1}
-> data.hex: 0x7B22686173686573223A312C22747873223A317D

> commit
-> code: OK
-> data.hex: 0x0000000000000001

> query "abc"
-> code: OK
-> log: Invalid query path. Expected hash or tx, got /store
-> height: 0

> deliver_tx "def"
-> code: OK

> commit
-> code: OK
-> data.hex: 0x0000000000000002

> query "def"
-> code: OK
-> log: Invalid query path. Expected hash or tx, got /store
-> height: 0
```

**Comment by ebuchman** [comment]
Can we fix the tutorial? 

Also the console stays open but under the hood the connection is being closed/reopened with each command because we're shelling it out, rather than continuing to call it in-process. When we originally reviewed that we said oh, it's not a big deal, but it is for this reason - we need to be able to test a persistent connection!

**Comment by odeke-em** [comment]
Alright so PR https://github.com/tendermint/abci/pull/117 that's pointed to.
