### ISSUE TITLE
types/types.pb.go: needs linting/`nolint` tag ...

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#138]
types.pb.go doesn't satisfy the `gas` linter since it doesn't check some errors.

we need to automatically add `//nolint: gas` above the `package` statement after running `protoc`.

At least until we get the Go protobuf team to lint their generated code.

@odeke-em :) ?

**Comment by odeke-em** [comment]
Oh crap I hadn't seen this tag, I am just seeing this. Let me take a look.

**Comment by odeke-em** [comment]
Alright, so I've explored a whole lot of options/ideas:
1. Using a shell hack such as `grep -Rn 'package \(\w\+\)$' types/*.pb.go | cut -d':' -f1 | while read F;do sed "s/package \([a-zA-Z]\{1,\}\)$/\/\/nolint: gas<NEWLINE_HEREXXXX>&/1" "$F" | awk -F"<NEWLINE_HEREXXXX>" '{ if (NF >= 2) { print $1"\n"$2 } else { print $1 } }';done`
2. Writing a small Go package to automatically do this either using "go/ast", "go/printer" to add these lines
3. Add PRs to the protobuf package to accept package flags 

The simplest, most elegant and most programmatic is option 1 which we can add as a directive or as a sub bash script to be run on every invocation of `make protoc`
