### ISSUE TITLE
Getting broken peer -to-peer tendermint connection on deliver_tx command execution using abci-cli

### ISSUE THREAD

**Issue by amrish54** [tendermint/abci#143]
**Requirement** : We want to perform transaction (for dummy application) on peer-to-peer network 

We have followed following  steps:

1.   Setup tendermint and `abci-cli` on two different server
2.   Run `abci-cli dummy` on both server
3.   Open new terminal and run tendermint p2p connection on both server
4.   Again open new terminal for one server and execute `abci-cli console`
5.   Execute `deliver_tx "abc"` got this error http://imagizer.imageshack.com/img922/4708/QKouyv.png

**Comment by ebuchman** [comment]
Aha! Please note that `abci-cli` commands like `deliver_tx` should only be used when testing an application on a single machine, without also running tendermint. When running the app with `tendermint`, `tendermint` is in charge of sending txs and takes the place of `abci-cli`. If you use `abci-cli` to send a tx, tendermint won't know about it, and will get very confused indeed. If you want to send transactions while running tendermint, use the `/broadcast_tx_commit` rpc endpoint. See more details here: https://tendermint.readthedocs.io/en/master/getting-started.html

I will close this issue, but please re-open or open a new one if you can't get it working :)

**Comment by amrish54** [comment]
thnx :)

**Comment by melekes** [comment]
I think we need to make this clear in the docs (or check) "Please note that abci-cli commands like deliver_tx should only be used when testing an application on a single machine, without also running tendermint"
