### ISSUE TITLE
Human Readable Error Codes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#146]
https://github.com/tendermint/abci/pull/145 removes CodeType, making the codes just `uint32`.

So now we have no generic means to get a string describing the error.

We could try something like

```
type CodeType struct {
    Code uint32
    Desc string
}

func NewCodeType(code uint32, desc string) CodeType {
    return CodeType{code, desc}
}

func (c CodeType) String() string{
    return c.Desc
}
```

But it's not great because now that string is being marshalled and passed around everywhere.

Another possibility is some kind of "registration" model.

Not thrilled with either yet

**Comment by odeke-em** [comment]
@ebuchman if these Codes are only declared in the `types` package, then how about this:
Let's keep CodeType as a uint32 type but then have a map to retrieve the string representation such that say
```go
type CodeType uint32

var codeTypeErrors = map[CodeType]string {
   CodeTypeOK: "OK",
   CodeTypeBadSync: "Bad sync",
}
const genericErrorMessage = "unexpected error"
func (ct CodeType) String() string {
    msg := codeTypeErrors[ct]
    if msg == "" {
       msg = genericErrorMessage
    }
    return msg
}
```

That above solves the worry about increased payload when marshalling and transporting things around, but also keeps CodeType as a uint32 and also ensures that CodeType implements `fmt.Stringer` with the `String()` method.

**Comment by ebuchman** [comment]
The challenge is that ABCI no longer specifies the codes - its up to the application. So for this package to know about them for printing, it would have to have some global registration object that applications could register code names with.

**Comment by coriolinus** [comment]
The natural solution from the application side is to declare some consts in a code module:

```go
package code
// Use `go generate` to create the ReturnCode stringer
//go:generate stringer -type=ReturnCode
type ReturnCode uint32
const (
	OK ReturnCode = iota
	...
)
```

This uses a standard generation package such that `ReturnCode` implements `fmt.Stringer`.

A natural interface for the registration function to accept an example object of type `fmt.Stringer`—it would probably be best to require that the OK value is used as the example—and then use reflection to get the example's type. From there, one could simply typecast the actual value as the example's type, in this case `ReturnCode`, and finally call its `.String()` method to get a nice human-readable representation.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1850
