### ISSUE TITLE
MOAR TESTS

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#150]
We would benefit from lots more unit tests here.

Eg https://github.com/tendermint/abci/blob/develop/types/messages_test.go#L14

**Comment by odeke-em** [comment]
Yeah I noticed a low test coverage too in types and others
```shell
$ cd types && go test -cover
PASS
coverage: 6.4% of statements
ok  	github.com/tendermint/abci/types	0.014s
```
at the latest develop 310beae63c4fee549faea4a6d4c0d9e027e5a707

**Comment by odeke-em** [comment]
The protobuf generated file `types.pb.go` is massive though, and skews these numbers by a whole lot as it doesn't serve us any purpose to test this generated code.

**Comment by ebuchman** [comment]
We're using gogo/protobuf now and I think they can actually generate tests for you. Want to take a look at that?

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1849
