### ISSUE TITLE
Unexpected result type *types.Response_Flush when response to *types.Request_Info expected

### ISSUE THREAD

**Issue by melekes** [tendermint/abci#178]
From riot:
```
Hi I see this error in logs when tried to connect a abci application to a tendermint node running on a docker container:  Stopping abci.socketClient for error: Unexpected result type *types.Response_Flush when response to *types.Request_Info expected module=abci-client connection=query. On abci-cli logs:- Connection was closed by client              module=abci-server  .
```

Tendermint version: 0.15.0
abci-cli: 0.9.0

How to reproduce:
???

**Comment by SurabhiBorgikar** [comment]
Steps to reproduce. Tendermint version is 0.13.0 which is the latest docker image from dockerhub. abci-cli: 0.9.0

1.Start tendermint container using:  `docker run -it --rm -v "/tmp:/tendermint" tendermint/tendermint node --proxy_app="tcp://172.17.0.2:46658"`

2. Start a dummy ABCI application using: `abci-cli dummy`

Result:
Tendermint container logs:  `Stopping abci.socketClient for error: Unexpected result type *types.Response_Flush when response to *types.Request_Info expected module=abci-client connection=query`  

abci-cli logs: `E[01-08|04:14:50.347] Connection was closed by client              module=abci-server`

**Comment by ethanfrey** [comment]
Hmmm... Request/Response_Flush is supposed to be silently generated by the proxy app to ensure the tcp buffer is flushed, then removed from the other end. This works with the apps we wrote with the sdk. I didn't realize many people used `abci-cli dummy`. Will investigate

**Comment by ramene** [comment]
I've managed to get this working using `Dockerfile` located under https://github.com/tendermint/tendermint/blob/master/test/docker/Dockerfile

```
git clone
docker build -t tendermint/tendermint:tester -f ./test/docker/Dockerfile .
```

`Dockerfile`

```
FROM golang:1.9.2

# Add testing deps for curl
RUN echo 'deb http://httpredir.debian.org/debian testing main non-free contrib' >> /etc/apt/sources.list

# Grab deps (jq, hexdump, xxd, killall)
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  jq bsdmainutils vim-common psmisc netcat curl

# Setup tendermint repo
ENV REPO $GOPATH/src/github.com/tendermint/tendermint
WORKDIR $REPO

# Install the vendored dependencies before copying code
# docker caching prevents reinstall on code change!
ADD glide.yaml glide.yaml
ADD glide.lock glide.lock
ADD Makefile Makefile
RUN make get_tools
RUN make get_vendor_deps

# Install the apps
ADD scripts scripts
RUN bash scripts/install_abci_apps.sh

# Now copy in the code
COPY . $REPO

RUN go install ./cmd/tendermint

# expose the volume for debugging
VOLUME $REPO

EXPOSE 46656
EXPOSE 46657

ENTRYPOINT ["tendermint"]

CMD ["node", "--proxy_app=tcp://0.0.0.0:46658"]
```

In terminal A:
`docker run -it --rm -p 46656:46656 -p 46657:46657 -v "$(pwd)":/root/.tendermint ramene/tendermint:tester node --proxy_app="tcp://172.17.0.3:46658"`

In terminal B:
`docker run -it --rm -p 46656:46656 -p 46657:46657 -v "$(pwd)":/root/.tendermint ramene/tendermint:tester node --proxy_app="tcp://172.17.0.3:46658"`

**Comment by ebuchman** [comment]
> Steps to reproduce. Tendermint version is 0.13.0 which is the latest docker image from dockerhub. abci-cli: 0.9.0

I think these are not compatible, which might explain why. 0.9 works with 0.15.

Sounds like this issue has been solved. Please open another or more specific one if there's still problems.
