### ISSUE TITLE
Document GRPC version

### ISSUE THREAD

**Issue by jaekwon** [tendermint/abci#18]
In addition to the bare TCP/Unix socket version, which is faster, there is now also support for a GRPC version, which is slower (but potentially easier to implement if you like GRPC).

Document this.

**Comment by tomtruitt** [comment]
one potentially important discovery Ethan shed light on was that while TMSP without GRPC length prefixes messages, with GRPC does not.

**Comment by ebuchman** [comment]
made mention of this in the readme. not sure how much more we need to document

**Comment by tomtruitt** [comment]
Is that to me or jae? I think it wasn't immediately obvious our team that grpc didn't length prefix messages, that it would be different from TMSP in that way. And so we were confused until you told us. I didn't catch that in the readme but maybe I missed it

**Comment by tomtruitt** [comment]
"Note this prefixing does not apply for grpc." 👍😂❤

**Comment by adrianbrink** [comment]
This should probably be closed too.
