### ISSUE TITLE
How can I initialize application from the abci-cli

### ISSUE THREAD

**Issue by pavlovdog** [tendermint/abci#181]
It's pretty unclear, how can I debug my application with `abci-cli`. Because, in the most cases, I should firstly call app's `init` method, but there's nothing even close in the list of commands, given by the `abci-cli help`.

Thanks in advance!

**Comment by ebuchman** [comment]
Great point - unfortunately you'll need to wait for https://github.com/tendermint/abci/issues/88 or implement initialization in your app

I'll close this in favour of that
