### ISSUE TITLE
[RFC] RequestQuery update

### ISSUE THREAD

**Issue by jaekwon** [tendermint/abci#182]
The design constraint that I strongly support for Query is for it to be feature compatible with HTTP queries.  So that means, the RequestQuery.Path should be the URL path, and it may or may not include the parameters... we should probably make RequestQuery.  Currently it is only:

```proto
message RequestQuery {
  bytes data = 1;
  string path = 2;
  int64 height = 3;
  bool prove = 4;
}
```

How about we evolve it toward:

```proto
message RequestQuery {
  bytes data = 1; // in case Query came as a POST, and the query includes bytes.
  string path = 2; // e.g. the URL path
  // int64 height = 3; DEPRECATED
  // bool prove = 4; DEPRECATED
  repeated common.KVPair params = 5; // "h"/"height" and "p"/"prove" are params here.
  repeated accept string = 6; // Similar to HTTP "Accept" header, e.g. "json" or "wire".  "json/unpack" or "wire/unpack" could mean, use the specific ResponseQuery fields, otherwise the response bytes can just be in the ResponseQuery.value field as bytes.
}
```

ResponseQuery doesn't need to change.  We can use ResponseQuery.value for now and later add support for "/unpack", if we want it.

**Comment by ethanfrey** [comment]
I do not like this.

We should pick an internal format that is clearly parsed, with clear semantics. What we currently have with the object. This can be converted to/from JSON/URI/protobuf/HTML/etc. We do not want to worry about that in the abci interface. That is trying all the parts too tightly together.

The current abci QueryRequest is basically fine. I suggest we just add the parsing code in the RPC server to convert that into a QueryRequest object. If there are new fields we need, we should add them.

But generic repeated common.KVPair is even worse than the type Values map[string][]string we get from net/http

I don't want to add random string parsing that came directly from an untrusted user into the abci app. This is asking for trouble. By having the tendermint rpc parse it carefully into a cannonical form, we can limit the error cases in the abci side. and allow the rpc interface to evolve without having to modify every abci app (many which will not use cosmos-sdk).

If you want to add 2 or 3 more fields with clear semantics to the Query to convey more info, please propose those cases, I am all ears. But just adding a bunch more string and key pairs to be parsed later.... seems risky and bug-prone.

**Comment by melekes** [comment]
@jaekwon do we have any use-cases clearly demonstrating need for this change? what was the driver for this proposal? Also

```
message RequestQuery {
  repeated accept string = 6; // Similar to HTTP "Accept" header, e.g. "json" or "wire".  "json/unpack" or "wire/unpack" could mean, use the specific ResponseQuery fields, otherwise the response bytes can just be in the ResponseQuery.value field as bytes.
}
```

should be a part of headers field if we want HTTP like construct

```
message RequestQuery {
  repeated common.KVPair headers = 6; // Similar to HTTP headers (including accept e.g. "json" or "wire".  "json/unpack" or "wire/unpack")
}
```

@ethanfrey I agree, but I also think the current interface may be not ideal for our users. Who knows? Maybe they don't like/use this "HTTP like" query interface at all and would prefer using something http://graphql.org/ like.

> I don't want to add random string parsing that came directly from an untrusted user into the abci app.

good argument, but what is so dangerous about calling `string(key)`? we'll be forced to write `params` parsing ourselves, yes... plus tests.

**Comment by zramsay** [comment]
should this go in an ADR or can we close the issue?

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1884
