### ISSUE TITLE
Custom address for ABCI example app

### ISSUE THREAD

**Issue by MarcoFavorito** [tendermint/abci#183]
FEATURE REQUEST

Now, if I'm not wrong, the listen address of example applications (i.e. `abci-cli dummy` and `abci-cli counter`) is equal to the default (`tcp://0.0.0.0:46658`).
Why don't make it settable from command line?

**Comment by zramsay** [comment]
check out the global flag: `--address string     Address of application socket (default "tcp://0.0.0.0:46658")`
