### ISSUE TITLE
Getting broken peer -to-peer tendermint connection on deliver_tx command execution using abci-cli

### ISSUE THREAD

**Issue by amrishfootprintlabs** [tendermint/abci#210]
Everything related to abci execution software already installed on our 2 servers.

After setup , We have followed following steps

1.We  have connected 2 server from our VM 

2. Run abci-cli dummy ( on ABCI Dummy app) on both server 

3.Open new terminal and run tendermint p2p connection on both server (tendermint node --p2p.seeds=........)

4.and again open new terminal for one server and execute abci-cli console

5.execute deliver_tx "abc" then we get error https://s.nimbus.everhelper.me/share/1524977/drcbw662bvfhl33smfxw

**Comment by ebuchman** [comment]
Don't run `abci-cli` if Tendermint is running. They will conflict with each other and cause errors like this. abci-cli is strictly for testing *without* running a Tendermint node.

If you want to send transactions, use the Tendermint RPC: https://tendermint.readthedocs.io/en/master/using-tendermint.html#broadcast-api
