### ISSUE TITLE
Validators: remove verbose sort.Interface methods in favour of sort.Slice

### ISSUE THREAD

**Issue by odeke-em** [tendermint/abci#212]
Raised offline by an auditor, and I totally see where they are coming from, the code for Validators implements that sort.Interface interface but doesn't conform to it with a compile type assertion to convey the message to auditors and other folks who are auditing method by method.
https://github.com/tendermint/abci/blob/68592f4d8ee34e97db94b7a7976b1309efdb7eb9/types/util.go#L11-L26

Tendermint now runs on Go1.8+ hence we can can now simply invoke
```go
sort.Slice(validators, func(i, j int) bool {
   return bytes.Compare(v[i].PubKey, v[j].PubKey) <= 0
})
```
It would be nicer to get rid of the older verbose code and keep things less ambiguous. This will help reduce the code base, keep it modern, reduce the API surface but even better not trigger redlights for anyone inspecting method by method.

**Comment by odeke-em** [comment]
Alright, the fix for this is just to compile time assert sort.Interface and also document it, because Validators is used spuriously so changing out to use sort.Slice would be tedious and very involved.

**Comment by ebuchman** [comment]
merged the comments. We should still consider a new SortValidators function ala https://github.com/tendermint/abci/pull/213#issuecomment-373113425 but its basically a TODO in the code and low priority thanks to the comment.
