### ISSUE TITLE
Canonical List of Special RequestQuery.Path values

### ISSUE THREAD

**Issue by coriolinus** [tendermint/abci#217]
I'm having a hard time figuring out what the "standard" query path set is. Most are defined by the ABCI application, ok, but what are the minimal set which must be supported for an ABCI app to do its job properly?

So far, I see:

- `/p2p/filter/addr/<addr>`: from [here](http://tendermint.readthedocs.io/en/master/app-development.html#query-connection)
- `/p2p/filter/pubkey/<pubkey>`: from [here](http://tendermint.readthedocs.io/en/master/app-development.html#query-connection)

I'm fairly sure that `/key` was also mentioned in documentation, but I can no longer find the reference.

Are there any such standard paths?

**Comment by ebuchman** [comment]
Thanks for raising this. 

I just updated the Tendermint spec in tendermint/tendermint#1500 to include this: https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/abci.md#query

Tendermint has no hard dependencies on Query, other than it returns 0 for those queries (else we'll never connect to peers).

Nothing else is enforced right now, though the [ABCI spec suggests](https://github.com/tendermint/abci/blob/master/specification.rst#query) apps must implement `/store`, though currently the SDK (our flagship app) does not. We will reconcile this (see tendermint/tendermint#1502).

Closing this now, but please re-open if something is not clear or you have more questions.

Thanks!!

**Comment by ebuchman** [comment]
I think `/key` was used once upon a time as a path in Basecoin, but is no longer.

We will provide detailed specification of how Query works in the SDK shortly as an example of an application with more advanced query functionality.
