### ISSUE TITLE
Explicit mempool ordering logic as a feature of abci 

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/abci#224]
From Zaki at #dev-tendermint:
Explicit mempool ordering logic as a feature of abci keeps coming up as a feature request.

### ABCI Mempool Management API

As we've discussed earlier, one of the quirks we ran into was a lack of control over the ordering of transactions in the mempool over ABCI. Being able to have finer grained control over the mempool would enable us to more rapidly create and test certain scenarios and edge cases on our protocol. We feel as though this would be useful to other users of TM Core/ABCI, and we realize that it's not a trivial change to the ABCI interface, as every application building on top of it has different notions of identity and transaction validity and thus there's no real "one-size-fits-all" mempool structure. Perhaps simply having the option to have the backend manage the entire mempool would be a powerful enough abstraction.

**Comment by ebuchman** [comment]
Is there a more concrete proposal for this ? If so can it be re-opened in Tendermint? Also probably post-launch anyways. Thanks!
