### ISSUE TITLE
Add merkle-eyes support to dummy

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#23]

**Comment by adrianbrink** [comment]
@ebuchman Do you mean updating it so that it works like [this](https://github.com/tendermint/merkleeyes/blob/master/app/app.go)?

**Comment by adrianbrink** [comment]
tags: easy

**Comment by ebuchman** [comment]
More that dummy could use either the go-merkle or the merkleeyes libs for its state. If merkleyes clients satisfy merkle.Tree, we can just pass the instance we want into NewDummyApp, and let it be a flag in the dummy cli

**Comment by ethanfrey** [comment]
Exactly what I want. A Merkle eyes client that has the same api as calling the Merkle tree in process.  Not trying to ring it through the abci interface. 

Of course, when you are querying multiple trees by holding references, you will need some way to represent those states as well. 

I think I wrote up my ideas a while ago in tendermint docs architecture

**Comment by ethanfrey** [comment]
Moving to remove merkleeyes as abci app and provide other interface.  I think this issue is deprecated?
