### ISSUE TITLE
AbsentValidators by address

### ISSUE THREAD

**Issue by b00f** [tendermint/abci#231]
To retrieve absent validators in each round is better to pass their address instead of their index in set.
```
func (m *RequestBeginBlock) GetAbsentValidators() []address {
...
}
```

**Comment by ebuchman** [comment]
merged to develop

**Comment by b00f** [comment]
Thanks for updating the api. By the way I think it will be awesome if you can provide Validators who has signed the proposal. 
In this case any time a block begins we will have full information about signing status: who has signed, who was byzantine and who was absent...

Just as a suggestion...

**Comment by ebuchman** [comment]
Validators who did sign is just everyone besides those who are Absent.

Should we really put it explicitly in the API or can we just assume that the app can figure out what "everyone besides AbsentValidators" means?

**Comment by b00f** [comment]
I think it's necessary. Imagine I have updated validators list in previous EndBlock and still tendermint didn't apply the changes (I have seen this in my tests before, tendermint takes time to change the validator set, maybe 2 or 3 rounds) so in this case the signed validator is not necessarily the validator who are not absent in application layer.
By the way, providing this information makes API more general and with detailed information.

Thanks

**Comment by ebuchman** [comment]
> Imagine I have updated validators list in previous EndBlock and still tendermint didn't apply the changes (I have seen this in my tests before, tendermint takes time to change the validator set, maybe 2 or 3 rounds) so in this case the signed validator is not necessarily the validator who are not absent in application layer.

This should never happen. The validator set change should take place immediately in the next block. If not, it's a bug!

That said, we actually plan to change this so it will be delayed by one block which is necessary for more efficient light clients: https://github.com/tendermint/tendermint/issues/1313

> By the way, providing this information makes API more general and with detailed information.

Fair enough

**Comment by ebuchman** [comment]
I have included your suggestions in https://github.com/tendermint/abci/pull/245/files - please take a look!

**Comment by b00f** [comment]
Thanks.
