### ISSUE TITLE
Change absent validator representation to public keys instead of indices

### ISSUE THREAD

**Issue by cwgoes** [tendermint/abci#239]
If absent validators are passed back as indices into a lexicographically sorted address array, ABCI applications must continually store/update such an array, which in most cases they would probably not otherwise need to do. Instead pass back absent validators by public key, as in `abci.Evidence` already. This adds a bit of extra communication overhead, but not too much and it only happens once per block.

This will be a *breaking* change for anyone using `RequestBeginBlock.AbsentValidators`.

**Comment by ebuchman** [comment]
Pubkeys or addresses?

Already changed to `bytes` on develop, but technically could still be either pubkey or address!

**Comment by cwgoes** [comment]
Ah sorry, I was looking at master, `bytes` is perfect.

**Comment by ebuchman** [comment]
tagging https://github.com/tendermint/abci/issues/231
