### ISSUE TITLE
`abci-cli kvstore` command doesn't work?

### ISSUE THREAD

**Issue by Deegrin** [tendermint/abci#246]
I built this from source and I'm getting the following error when executing `abci-cli kvstore`:

```david@david ~ $ abci-cli kvstore
Error: unknown command "kvstore" for "abci-cli"
Run 'abci-cli --help' for usage.
unknown command "kvstore" for "abci-cli"
```

Am I missing something? Has it been disabled? I'm also interested in writing a small example application for familiarizing myself with Tendermint, so I'd like to see this in-process method work. Thank you in advance!

**Comment by ebuchman** [comment]
What version are you on ? If you update to the latest (master branch, v0.10.3) it should work fine.

The `kvstore` used to be called `dummy`, so that might work

**Comment by Deegrin** [comment]
Ah, rookie mistake! $PATH was pointing to an older Tendermint ABCI installation. Thank you!!
