### ISSUE TITLE
Not only use minor version for grpc dependency

### ISSUE THREAD

**Issue by GrapeBaBa** [tendermint/abci#248]
grpc lib is a common library in many golang application, right now abci can be conflict with others when other application use higher grpc version. I'd like to remove this limitation.

**Comment by GrapeBaBa** [comment]
v0.10.3: Could not introduce github.com/tendermint/abci@v0.10.3, as it has a dependency on google.golang.org/grpc with constraint ~1.7.3, which has no overlap with existing constraint 1.11.3 from (root)

**Comment by ebuchman** [comment]
Ok - any chance you could make a PR for this and ensure it works both here and in Tendermint?

I've found in the past that upgrading GRPC version can be a bit of a rabbit hole and we just dont have enough capacity to really spend on that right now.

Thanks!

**Comment by GrapeBaBa** [comment]
@ebuchman yeah, I'd like to make a PR when #247 merged.

**Comment by ebuchman** [comment]
Coool - merged to develop!

**Comment by zramsay** [comment]
moved to https://github.com/tendermint/tendermint/issues/1883
