### ISSUE TITLE
Support Range Query

### ISSUE THREAD

**Issue by xiaoxiaff** [tendermint/abci#250]
For now the abci ResponseQuery only support single value and proof result. When it comes to range query it would fail to support that. Is there any plan about support range query?

**Comment by ebuchman** [comment]
Yes we're going to change this to be a range proof. See the latest work in the IAVL repo that will support this: https://github.com/tendermint/iavl/pull/63

**Comment by zramsay** [comment]
https://github.com/tendermint/iavl/pull/63 is merged on develop
