### ISSUE TITLE
Block header information at certain height

### ISSUE THREAD

**Issue by b00f** [tendermint/abci#257]
It will be useful if ABCI can provide bock header information at certain height.

**Comment by ebuchman** [comment]
The block header is included in the ReqestBeginBlock for every height

**Comment by b00f** [comment]
@ebuchman Is there any way for application to get bock header information at a given height? I don't mean only previous height . For example if the current height is `n`, can application request for header information at block '`n-10`.

**Comment by ebuchman** [comment]
> For example if the current height is n, can application request for header information at block n-10

Not via ABCI. It can easily do this via the tendermint RPC though with `/block?height=10`

**Comment by b00f** [comment]
@silasdavis has suggested to get this information via ABCI not RPC. Do you think getting this information from RPC will cause Race Condition. Please take a look here: https://github.com/hyperledger/burrow/pull/780#discussion_r191446259

**Comment by ebuchman** [comment]
You can specify which height you want the information from, or ask for the latest height by just doing `/block` without the `height` parameter. 

ABCI isn't symetric - it's not designed to allow for the app to query Tendermint. If the app needs something, it should be able to get it from the RPC

**Comment by b00f** [comment]
This is what we did right now. I think better to keep it close for now. Thanks
