### ISSUE TITLE
Application custom data in block header

### ISSUE THREAD

**Issue by b00f** [tendermint/abci#259]
At the moment block header stores application hash. It will be very useful if application can have some custom data related to a specific block next to the application hash.
For example application can store block rewards (fee) inside the block header.  This can be done when the block is committing.

**Comment by silasdavis** [comment]
Is there a reason the application could not just store this data itself or transmit it in transactions?

**Comment by b00f** [comment]
I know that it sounds a bit dangerous, but I think providing this ability helps application to access some information easily by referring to the block header. Application itself SHOULD make sure that this data is deterministic and provable.

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1855
