### ISSUE TITLE
Dont send PubKeys in BeginBlock

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#276]
Addresses will be easier to compute (hash of the raw pubkey bytes). But pubkeys are large and will only get larger, we can't sustainably send them. Apps should deal in addresses.

Of course Apps will still need to return PubKeys in EndBlock to update the validator set.

**Comment by b00f** [comment]
> Of course Apps will still need to return PubKeys in EndBlock to update the validator set.

Hopefully one day App and Tendermint can work together just with address!

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/issues/1860
