### ISSUE TITLE
Make abci-cli output more machine parseable

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#32]
either pack it all in json or just print the code and the data

**Comment by rigelrozanski** [comment]
You mentioned - The point of making the output machine readable is to simplify some of the tests or to make it easier to write more. Would it not still make sense to still use JSON but maybe come up with a consistent struct to feed (which includes error etc.) rather an information dump as in initial PR #41 ?

**Comment by adrianbrink** [comment]
This has been dealt with in #46 and should be closed.

**Comment by ebuchman** [comment]
dont think so https://github.com/tendermint/abci/pull/41#issuecomment-269105207

**Comment by zramsay** [comment]
tendermint docs:

The result should look like:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "response": {
      "code": 0,
      "index": 0,
      "key": "",
      "value": "61626364",
      "proof": "",
      "height": 0,
      "log": "exists"
    }
  }
}
```
Note the value in the result (61626364); this is the hex-encoding of the ASCII of abcd. You can verify this in a python shell by running "61626364".decode('hex'). Stay tuned for a future release that makes this output more human-readable.
