### ISSUE TITLE
Cannot add custom abci error codes

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/abci#44]
Maybe I am wrong... but as far as I can tell, when I want to return an error from my tmsp app, it must be of `tmsp/types.CodeType`, something like `types.CodeType_BaseDuplicateAddress`.  These types are all defined in the protobuf file, which is fine for the builtin apps....

But, if I want to add an error type for my app to return.  How do I do it?  Forking tmsp and editing the protobuf file seems a bit heavy to add an error code.

Or maybe we need more generic types.  Clearly the existing generic types weren't enough for basecoin and governmint...

I'd love to hear more feedback here.

**Comment by jaekwon** [comment]
Yeah good point, we have to support other values that the App wants to support.  We should probably reserve a large range for apps to create their own codes.

Protobuf3 spec says:

```
During deserialization, unrecognized enum values will be preserved in the message, though how this is represented when the message is deserialized is language-dependent. In languages that support open enum types with values outside the range of specified symbols, such as C++ and Go, the unknown enum value is simply stored as its underlying integer representation. In languages with closed enum types such as Java, a case in the enum is used to represent an unrecognized value, and the underlying integer can be accessed with special accessors. In either case, if the message is serialized the unrecognized value will still be serialized with the message.
```
https://developers.google.com/protocol-buffers/docs/proto3

But I'm not sure how various implementations actually are.

I'm honestly not sure what the best solution is here.

**Comment by adrianbrink** [comment]
tags: needs-investigation, discussion

**Comment by ethanfrey** [comment]
It seems bucky used this in the ibc app to use arbitrary codes he wanted that were not defined elsewhere.  Works for me.

**Comment by ebuchman** [comment]
We should probably still review/finalize the current set of ABCI codes

**Comment by ebuchman** [comment]
built in error codes have been removed. Only OK is built in now. The examples use their own code scheme in example/code :)
