### ISSUE TITLE
change `--abci socket` to `--abci tsp`

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#52]

**Comment by adrianbrink** [comment]
@ebuchman Could you elaborate on this?

**Comment by ebuchman** [comment]
At one point I thought we'd call the "socket" based (as opposed to grpc based) version of ABCI as "TSP" -> Tendermint Socket Protocol or Teaspoon for short (the blockchain serves the app with a silver teaspoon). I think Jae vetoed it.
