### ISSUE TITLE
Compiling Tendermint and abci app into single binary

### ISSUE THREAD

**Issue by erikreppel** [tendermint/abci#69]
I read in your slack that it is possible to compile a single binary that consists of a tendermint node and an abci application. Going through your code, my best attempt has been [this](https://gist.github.com/erikreppel/33e7e09a052d2b992425994033b0bde0)

The issue I'm running into is because tendermint uses a vendored copy of `abci/types` I run into this:

```
 $ go run main.go                                                                             [22:43:30]
# command-line-arguments
./main.go:43: cannot use example.NewExampl() (type *example.Example) as type "github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/types".Application in argument to proxy.NewLocalClientCreator:
	*example.Example does not implement "github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/types".Application (wrong type for BeginBlock method)
		have BeginBlock([]byte, *"github.com/tendermint/abci/types".Header)
		want BeginBlock([]byte, *"github.com/tendermint/tendermint/vendor/github.com/tendermint/abci/types".Header)
```

Do you guys have any way around this or any good resources on compiling single binaries? Any help is much appreciated!

**Comment by erikreppel** [comment]
Update: managed to compile a single binary by vendoring all dependancies in my project.
```
$ glide init
$ glide install
$ go build
```

**Comment by ethanfrey** [comment]
:+1: 

@erikreppel you can also look at https://github.com/tendermint/basecoin for an example of a command that compiles in tendermint, but it seems like you did it well.
