### ISSUE TITLE
Enable multiple ABCI apps behind the same tendermint core network

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/abci#74]
FEATURE REQUEST

It might be interesting to enable the functionality that multiple ABCI apps can run behind the same tendermint core consensus network.

For example, we have the dummy and the counter app and both are verified by the same validator set.

**Comment by srmo** [comment]
would this need too much logic in core, i.e. the core would have to know about tx semantics? How will the core determine which app should be asked for transaction validation? In my oppionion, it is sufficient to have the ABCI app bundle different logic. Maybe communicate with different apps by relaying check/deliverTX et al to the appropriate app depending on the transaction type

**Comment by adrianbrink** [comment]
Tag: feature request

**Comment by adrianbrink** [comment]
I'm closing this, since with basecoin and basecoin plugins we can achieve a similar effect.
