### ISSUE TITLE
Test suite for evaluating implementations for bounty

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#76]
There's some scripts that test eg. the "first abci guide" stuff. We should abstract this so it's easier to run on new implementations. Also, we should add an integration test to see it run with tendermint.

A successful implementation should come with a docker file so the server and app can be easily started. We can then run a series of txs and ensure things act as expected.

@adrianbrink want to work on this?

**Comment by adrianbrink** [comment]
@ebuchman Cool, on it.

**Comment by adrianbrink** [comment]
The plan:

- add a command ```test``` on the abci-cli that runs a test suite of our choosing against the Counter app

This would allow bounty hunters to write their ABCI server (in their language) and always see the whether the tests are passing and what tests are still failing.
It will also allow us to specify the ABCI protocol by building a comprehensive test suite for it.

**Comment by adrianbrink** [comment]
Implementation in: #83

**Comment by KrzysiekJ** [comment]
Since the PR has been closed and this issue has been unassigned, what is its status? Will bounty claims be resolved without automated tests?

**Comment by ebuchman** [comment]
Thanks for the ping. We've all congregated for a week and this is on the agenda. We'll have a real update by weeks end.

**Comment by KrzysiekJ** [comment]
So what is the status of this? :)

**Comment by ebuchman** [comment]
Thanks for checking in on this. We've obviously been too busy to give this the time of day :(

Think this is something you'd have time to take a crack at ?

**Comment by KrzysiekJ** [comment]
I’m not a Go programmer, so, unless there are little changes needed in #83, it would probably be problematic.

**Comment by adrianbrink** [comment]
@KrzysiekJ I can mentor you on this. Go is not a hard language and the basics are all there. If you want to take a crack at it let me know and we can connect on RocketChat.

**Comment by KrzysiekJ** [comment]
Ok, I’m willing to give it a try (writing here after being advised to do so on chat). Can you describe what is missing in #83?

**Comment by adrianbrink** [comment]
Mh, I think you should reopen the PR and try and run it. Then make sure that everything still works and ideally add the ability to programmatically detect which tests failed.

**Comment by KrzysiekJ** [comment]
Can you push back the branch from the PR, so that it can be fetched?

**Comment by zramsay** [comment]
branch restored

**Comment by ebuchman** [comment]
Ok, thanks @KrzysiekJ for cleaning up. Here's what this still needs to be bounty ready:

- [ ] tests/server should have a struct that implements abci.Application so we can assert it supports all the ABCI methods
- [ ] tests/server should not use fmt.Println. It should wrap all its errors (https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully)
- [ ] we should be running multiple distinct tests. It's fine for now if they run one after another and depend on the state of the previous one - let's just be clear about that in the code
  - [ ] BlockSequenceTest - run InitChain followed Info followed by a few instances of the block sequence (BeginBlock, multiple DeliverTx, EndBlock, Commit) with invalid deliver txs (so they dont affect the state). We don't really care what Info returns or what BeginBlock/EndBlock do here, but they shouldn't return errors (ie. the server implements them even if the Counter treats them as NOPs)
  - [ ] TxTest - run a bunch of DeliverTxs and CheckTxs where some are valid and some are invalid.  Make sure running CheckTx doesn't effect the results of DeliverTx, but DeliverTx effects the results of CheckTx. Run C
  - [ ] CommitTest - run Commit. It should return the big-endian encoding of the txCount (ie. valid DeliverTxs sent so far). Run some more valid and invalid DeliverTx and run Commit again, make sure the result is correct.
  - [ ] QueryTest - run a Query for the "hash" and the "tx". "hash" should return the number of times we've called Commit, and "tx" the number of valid DeliverTx. Run some more DeliverTx and Commit, Query again, and confirm it was all updated right.

Note all CheckTx and DeliverTx should run via `Async`. Everything else can be `Sync`.

Also note that everything should be super neat and easy to see what's going on and easy to maintain, similar to how it looks now. 

Finally, we should clearly write the spec for the Counter (some of it is hidden in the above).

Then we can start rewarding people.

**Comment by KrzysiekJ** [comment]
If `tests/server` should not use `fmt.Println`, then do we want to retain reporting that an assertion for a singular call has passed? If so, then I guess we need to do something like wrapping each server call into a struct that encapsulates: string describing the assertion and a function to call.

The test command interacts with an external ABCI server. If we want to run multiple distinct tests, then we have no way to reset server state between tests.

**Comment by adrianbrink** [comment]
#162 
@KrzysiekJ If you want to add stuff, please add it there :-)

@ebuchman `abci.Application` seems strange. It would mean that the test client for the Counter application defines `Info(RequestInfo) ResponseInfo`.

**Comment by zramsay** [comment]
closing for https://github.com/tendermint/tendermint/issues/1848
