### ISSUE TITLE
Application return values

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#77]
Eg. Query should return new ResultQuery so it uses data.Bytes

**Comment by cloudhead** [comment]
Is this done?

I think also looking at the return types, we're mixing `Response` and `Result` - we should ideally stick to one or the other, easiest being to just rename `Result` to `Response`.

https://github.com/tendermint/abci/blob/develop/types/application.go#L9

**Comment by ebuchman** [comment]
yep removed Result. using `gogo/protobuf` lets us use data.Bytes in generated code directly. Woo!
