### ISSUE TITLE
ABCI results error tracing

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/abci#86]

**Comment by adrianbrink** [comment]
@rigelrozanski Could you provide some more info on what you mean?

**Comment by rigelrozanski** [comment]
Basically it would be awesome to implement something equivalent to pkg/errors for our error packages within abci.Result. So if you're passing back an error result from an abci call and a debugging (or logging?) option is set, you are able to get a stack trace to the origin of the abci error

**Comment by rigelrozanski** [comment]
melekes:
I’ve implemented the tracing logger which prints the stack trace if error contains it
so if abci returns an error with a stack trace, it will get printed

**Comment by ethanfrey** [comment]
@rigelrozanski The code is there to do this, but do we actually log errors in abci, or just return them.  I think it just involves setting up the logger properly and writing the errors to the logger.

**Comment by adrianbrink** [comment]
It's mixed. The server package uses the logger, but the client package doesn't.

**Comment by rigelrozanski** [comment]
Yeah it's been integrated. If you want error tracing on the client side, just use pkg/errors or panic
