### ISSUE TITLE
ABCI test suite to test ABCI servers

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/abci#89]
A bash script that runs all tests against the ABCI server and starts a tendermint node to check whether we can make blocks.

**Comment by ebuchman** [comment]
```
init_chain
set_option serial on
commit
deliver_tx abc
commit
deliver_tx 0x00
commit
deliver_tx 0x00
deliver_tx 0x01
deliver_tx 0x0002
deliver_tx 0x0003
deliver_tx 0x000004
deliver_tx 0x000006
commit
```

Note we should add begin/end block to this. We'll need to add init_chain to the cli and merge the begin/end block PR

**Comment by ethanfrey** [comment]
Wait, @adrianbrink  was this done or not? This seems to be a todo, but in slack you mentioned it was done?  If so, can you close this issue and reference the branch it was on?

**Comment by zramsay** [comment]
duplicate of #76
