### ISSUE TITLE
consolidate binaries

### ISSUE THREAD

**Issue by ebuchman** [tendermint/abci#95]
Should we consolidate `counter` and `dummy` into the `abci-cli` ? So something like `abci-cli counter` and `abci-cli dummy` ?

**Comment by melekes** [comment]
How would it help us?

**Comment by ebuchman** [comment]
Because otherwise we have multiple `counter` binaries that mean different things. One is the simple abci counter, the other is the basecoin counter. Both are called just `counter`. Also, the abci counter is just magically installed when you `go get github.com/tendermint/abci/cmd/...`. Also this way we could release one binary on the website, instead of bundling 3 ... So would be an overall simplification

**Comment by adrianbrink** [comment]
I am against cluttering the abci-cli with unrelated subcommands. We need an easy way to show people how COSMOS apps work. They should live by themselves instead of being mixed in with some other functionality.

Let’s remove all the example apps from inside the repos and let’s have them in an example repo under COSMOS.

**Comment by ebuchman** [comment]
These aren't cosmos related tho. These are raw, very simple ABCI apps. Their primary use is for testing a new ABCI implementation, and having quick and dirty apps to use to test tendermint with.

**Comment by zramsay** [comment]
i'm gonna make a doc that includes all of the repo/binary combination to give us a starting point ... there are a lot & i find more with every new repo I look through. see https://github.com/tendermint/coding/issues/12

**Comment by zramsay** [comment]
yeah these binaries don't belong in cosmos-academy. I will consolidate per bucky's original suggestion.

**Comment by zramsay** [comment]
this would trickle to affect: the README, tendermint docs, some tests, etc. Not worth making the change IMO. (Better to have good docs instead)

**Comment by ebuchman** [comment]
@zramsay I'll let this be your call but I'm not convinced, especially given that we'll have two `counter` apps - one here and one in the sdk. Better docs might solve it, but can also be confusing.

**Comment by zramsay** [comment]
done, see #117
