### ISSUE TITLE
failed to install dummy

### ISSUE THREAD

**Issue by kidinamoto01** [tendermint/abci#99]
after check out frpm repo, I ran 
`go install ./cmd/...`

then I got the following error:
# github.com/tendermint/abci/example/dummy
example/dummy/dummy.go:20: cannot use state (type *iavl.IAVLTree) as type "github.com/tendermint/tmlibs/merkle".Tree in field value:
	*iavl.IAVLTree does not implement "github.com/tendermint/tmlibs/merkle".Tree (wrong type for Copy method)
		have Copy() "github.com/tendermint/merkleeyes/vendor/github.com/tendermint/tmlibs/merkle".Tree
		want Copy() "github.com/tendermint/tmlibs/merkle".Tree
example/dummy/persistent_dummy.go:42: cannot use db (type "github.com/tendermint/tmlibs/db".DB) as type "github.com/tendermint/merkleeyes/vendor/github.com/tendermint/tmlibs/db".DB in argument to iavl.NewIAVLTree:
	"github.com/tendermint/tmlibs/db".DB does not implement "github.com/tendermint/merkleeyes/vendor/github.com/tendermint/tmlibs/db".DB (wrong type for Iterator method)
		have Iterator() "github.com/tendermint/tmlibs/db".Iterator
		want Iterator() "github.com/tendermint/merkleeyes/vendor/github.com/tendermint/tmlibs/db".Iterator
example/dummy/persistent_dummy.go:48: cannot use stateTree (type *iavl.IAVLTree) as type "github.com/tendermint/tmlibs/merkle".Tree in field value:
	*iavl.IAVLTree does not implement "github.com/tendermint/tmlibs/merkle".Tree (wrong type for Copy method)
		have Copy() "github.com/tendermint/merkleeyes/vendor/github.com/tendermint/tmlibs/merkle".Tree
		want Copy() "github.com/tendermint/tmlibs/merkle".Tree

**Comment by melekes** [comment]
Something wrong with the deps. Try executing glide (https://github.com/Masterminds/glide): `glide install` before `go get`

**Comment by zramsay** [comment]
@kidinamoto01 the instructions were updated in #100
